### ISSUE TITLE
Move ZFS Admin Guide out of staging & convert to DocBook 5

### ISSUE THREAD

**Issue by melloc** [rmustacc/illumos-docbooks#75]
@madwizard is working on updating the ZFS Admin Guide. I've finished converting it to DocBook 5, and it can be built with [dblatex](http://dblatex.sourceforge.net/). The XSLT stylesheets and validation process (along with other converted books/guides) will follow soon.

**Comment by rmustacc** [comment]
Resolved in ac10847.
